### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Technocyrex** [otakumods/Kramers#1]
It's says, 

VCRUNTIME140D.dll
ucrtbased.dll
VCRUNTIME140_1D.dll
MSVCP140D.dll

is missing, any help?

**Comment by 0verp0wer** [comment]
> It's says,
> 
> VCRUNTIME140D.dll ucrtbased.dll VCRUNTIME140_1D.dll MSVCP140D.dll
> 
> is missing, any help?

dm me on discord: ꧁𝕆𝕧𝕖𝕣𝕡𝕠𝕨𝕖𝕣༄꧂#2524
